// <auto-generated />
using System;
using BeneficentEvent.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BeneficentEvent.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("BeneficentEvent.Models.Benfeitor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Endereco")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefone")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Benfeitores");
                });

            modelBuilder.Entity("BeneficentEvent.Models.Bingo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataSorteio")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EventoId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ValorCartela")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EventoId");

                    b.ToTable("Bingos");
                });

            modelBuilder.Entity("BeneficentEvent.Models.Despesa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Data")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EventoId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Fornecedor")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Valor")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EventoId");

                    b.ToTable("Despesas");
                });

            modelBuilder.Entity("BeneficentEvent.Models.Doacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BenfeitorId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataDoacao")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EventoId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Observacao")
                        .HasColumnType("TEXT");

                    b.Property<int>("Tipo")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("ValorMonetario")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BenfeitorId");

                    b.HasIndex("EventoId");

                    b.ToTable("Doacoes");
                });

            modelBuilder.Entity("BeneficentEvent.Models.Evento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataFim")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Local")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Eventos");
                });

            modelBuilder.Entity("BeneficentEvent.Models.ItemDoacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DoacaoId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Quantidade")
                        .HasColumnType("TEXT");

                    b.Property<string>("Unidade")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ValorEstimado")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DoacaoId");

                    b.ToTable("ItensDoacao");
                });

            modelBuilder.Entity("BeneficentEvent.Models.ItemLeilao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("LanceAtual")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("LanceInicial")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LeilaoId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Lote")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LeilaoId");

                    b.ToTable("ItensLeilao");
                });

            modelBuilder.Entity("BeneficentEvent.Models.ItemVenda", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrecoUnitario")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProdutoId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Quantidade")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("VendaId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProdutoId");

                    b.HasIndex("VendaId");

                    b.ToTable("ItensVenda");
                });

            modelBuilder.Entity("BeneficentEvent.Models.Lance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BenfeitorId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ItemLeilaoId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Valor")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BenfeitorId");

                    b.HasIndex("ItemLeilaoId");

                    b.ToTable("Lances");
                });

            modelBuilder.Entity("BeneficentEvent.Models.Leilao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Data")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EventoId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EventoId");

                    b.ToTable("Leiloes");
                });

            modelBuilder.Entity("BeneficentEvent.Models.MovimentoFinanceiro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataMovimento")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EventoId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Origem")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Tipo")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Valor")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EventoId");

                    b.ToTable("MovimentosFinanceiros");
                });

            modelBuilder.Entity("BeneficentEvent.Models.ParticipacaoEvento", b =>
                {
                    b.Property<Guid>("EventoId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BenfeitorId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Funcao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Observacao")
                        .HasColumnType("TEXT");

                    b.HasKey("EventoId", "BenfeitorId");

                    b.HasIndex("BenfeitorId");

                    b.ToTable("ParticipacoesEvento");
                });

            modelBuilder.Entity("BeneficentEvent.Models.PremioBingo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BingoId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ValorEstimado")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BingoId");

                    b.ToTable("PremiosBingo");
                });

            modelBuilder.Entity("BeneficentEvent.Models.Produto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EventoId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrecoVenda")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("QuantidadeEstoque")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EventoId");

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("BeneficentEvent.Models.Venda", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataVenda")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EventoId")
                        .HasColumnType("TEXT");

                    b.Property<int>("FormaPagamento")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EventoId");

                    b.ToTable("Vendas");
                });

            modelBuilder.Entity("BeneficentEvent.Models.Bingo", b =>
                {
                    b.HasOne("BeneficentEvent.Models.Evento", "Evento")
                        .WithMany("Bingos")
                        .HasForeignKey("EventoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Evento");
                });

            modelBuilder.Entity("BeneficentEvent.Models.Despesa", b =>
                {
                    b.HasOne("BeneficentEvent.Models.Evento", "Evento")
                        .WithMany("Despesas")
                        .HasForeignKey("EventoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Evento");
                });

            modelBuilder.Entity("BeneficentEvent.Models.Doacao", b =>
                {
                    b.HasOne("BeneficentEvent.Models.Benfeitor", "Benfeitor")
                        .WithMany("Doacoes")
                        .HasForeignKey("BenfeitorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BeneficentEvent.Models.Evento", "Evento")
                        .WithMany("Doacoes")
                        .HasForeignKey("EventoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Benfeitor");

                    b.Navigation("Evento");
                });

            modelBuilder.Entity("BeneficentEvent.Models.ItemDoacao", b =>
                {
                    b.HasOne("BeneficentEvent.Models.Doacao", "Doacao")
                        .WithMany("Itens")
                        .HasForeignKey("DoacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doacao");
                });

            modelBuilder.Entity("BeneficentEvent.Models.ItemLeilao", b =>
                {
                    b.HasOne("BeneficentEvent.Models.Leilao", "Leilao")
                        .WithMany("Itens")
                        .HasForeignKey("LeilaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Leilao");
                });

            modelBuilder.Entity("BeneficentEvent.Models.ItemVenda", b =>
                {
                    b.HasOne("BeneficentEvent.Models.Produto", "Produto")
                        .WithMany("ItensVenda")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BeneficentEvent.Models.Venda", "Venda")
                        .WithMany("Itens")
                        .HasForeignKey("VendaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produto");

                    b.Navigation("Venda");
                });

            modelBuilder.Entity("BeneficentEvent.Models.Lance", b =>
                {
                    b.HasOne("BeneficentEvent.Models.Benfeitor", "Benfeitor")
                        .WithMany("Lances")
                        .HasForeignKey("BenfeitorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BeneficentEvent.Models.ItemLeilao", "ItemLeilao")
                        .WithMany("Lances")
                        .HasForeignKey("ItemLeilaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Benfeitor");

                    b.Navigation("ItemLeilao");
                });

            modelBuilder.Entity("BeneficentEvent.Models.Leilao", b =>
                {
                    b.HasOne("BeneficentEvent.Models.Evento", "Evento")
                        .WithMany("Leiloes")
                        .HasForeignKey("EventoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Evento");
                });

            modelBuilder.Entity("BeneficentEvent.Models.MovimentoFinanceiro", b =>
                {
                    b.HasOne("BeneficentEvent.Models.Evento", "Evento")
                        .WithMany("MovimentosFinanceiros")
                        .HasForeignKey("EventoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Evento");
                });

            modelBuilder.Entity("BeneficentEvent.Models.ParticipacaoEvento", b =>
                {
                    b.HasOne("BeneficentEvent.Models.Benfeitor", "Benfeitor")
                        .WithMany("Eventos")
                        .HasForeignKey("BenfeitorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BeneficentEvent.Models.Evento", "Evento")
                        .WithMany("Participantes")
                        .HasForeignKey("EventoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Benfeitor");

                    b.Navigation("Evento");
                });

            modelBuilder.Entity("BeneficentEvent.Models.PremioBingo", b =>
                {
                    b.HasOne("BeneficentEvent.Models.Bingo", "Bingo")
                        .WithMany("Premios")
                        .HasForeignKey("BingoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bingo");
                });

            modelBuilder.Entity("BeneficentEvent.Models.Produto", b =>
                {
                    b.HasOne("BeneficentEvent.Models.Evento", "Evento")
                        .WithMany("Produtos")
                        .HasForeignKey("EventoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Evento");
                });

            modelBuilder.Entity("BeneficentEvent.Models.Venda", b =>
                {
                    b.HasOne("BeneficentEvent.Models.Evento", "Evento")
                        .WithMany()
                        .HasForeignKey("EventoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Evento");
                });

            modelBuilder.Entity("BeneficentEvent.Models.Benfeitor", b =>
                {
                    b.Navigation("Doacoes");

                    b.Navigation("Eventos");

                    b.Navigation("Lances");
                });

            modelBuilder.Entity("BeneficentEvent.Models.Bingo", b =>
                {
                    b.Navigation("Premios");
                });

            modelBuilder.Entity("BeneficentEvent.Models.Doacao", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("BeneficentEvent.Models.Evento", b =>
                {
                    b.Navigation("Bingos");

                    b.Navigation("Despesas");

                    b.Navigation("Doacoes");

                    b.Navigation("Leiloes");

                    b.Navigation("MovimentosFinanceiros");

                    b.Navigation("Participantes");

                    b.Navigation("Produtos");
                });

            modelBuilder.Entity("BeneficentEvent.Models.ItemLeilao", b =>
                {
                    b.Navigation("Lances");
                });

            modelBuilder.Entity("BeneficentEvent.Models.Leilao", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("BeneficentEvent.Models.Produto", b =>
                {
                    b.Navigation("ItensVenda");
                });

            modelBuilder.Entity("BeneficentEvent.Models.Venda", b =>
                {
                    b.Navigation("Itens");
                });
#pragma warning restore 612, 618
        }
    }
}
